### ISSUE TITLE
Update the Guidline/Overview page and Get started/Coding page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#113]
> As a Cupcake website designer

> I need to: update the Guideline Overview page with the least guideline list from Carbon and add DDO information to the Coding page.

> so that: our adopters can find the most up to date information about Guidelines and how to get started with Coding. 

#### Additional information
- Current cupcake Guidelines overview page can be viewed [here](https://carbon-for-ibm.netlify.com/guidelines/).

- Current cupcake Get Started Coding page can be viewed [here](https://carbon-for-ibm.netlify.com/getting-started/coding).

#### Acceptance criteria
- [x] Content and design published with markdowns.
- [x] Content and design reviewed with Jenny and Wonil.
- [ ] Content and design accepted by Wonil and Linda.

**Comment by JennySanchez** [comment]
#### Items for update:

- Update the intro sentence.
- List out all the carbon guidelines and link them out and set them up in the table format with a high-level description of what they are (see Layout Patterns, Type table for reference).
- Add content around what is Guideline.
- Take out "Why do we need guidelines?"

@wonilsuhibm Can you confirm the list covers everything you mentioned?

**Comment by JennySanchez** [comment]
#### Items for Get started-Coding page update:
- Add the metadata or DDO content to the page or another proper spot for adopters to find it easily.

https://ibm.box.com/s/4dfljjgkm9qz3498fbq656qj5ws4r18u

**Nest step:** Work on this with Jeff. Work session set up for Wednesday 1:30 pm CST.
FYI - @jacobottesen-dgc

**Comment by jacobottesen-dgc** [comment]
Here is some potential content for the "What are guidelines?" section:
"Guidelines are a set of fundamentals that bring consistency to IBM’s product and online experiences. This guidance will provide you with a system for creative decision-making. The guidelines below will give you a starting point to design with consistency and quality."

@wonilsuhibm Can you provide some feedback?

**Comment by JennySanchez** [comment]
Based on the discussion today, we need to create a task issue for us to add a card on the Resources page for metadata and DDO content linking.

Task issue created - #128 for Sprint 24.

**Comment by JennySanchez** [comment]
Based on the feedback from Wonil. We will take out the "What is guideline?" and replace it with something that can connect to the guideline list below it better.

**Comment by JennySanchez** [comment]
**Task update:
- The Guideline page is published and can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/guidelines).

- The Coding page is published but needs to add Metadata and DDO content links. Jeff needs to set it up the content before we can make the update on the website. Task issue #128 is created for the update.
