### ISSUE TITLE
Cupcake website - Footer and Masthead content update

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/carbon-for-ibm-website#60]
> As an: Cupcake website content creator

> I need to: update the content for the Masthead and Footer pages

> so that I can: match the way Carbon website content layout.

#### Additional information
- Our current Footer and Masthead content can be viewed via the links below:

#### Task
- Collaborate with Jenny for content updates.

#### Acceptance criteria
- [x] Content reviewed with Jenny.
- [x] Content updated on the live website.
- [ ] Page content accepted by Wonil and Linda

**Comment by jacobottesen-dgc** [comment]
I've made all of the following updates:

    - Add footer demo images
    - Add masthead demo images
    - Add documentation table to footer
    - Add documentation table to masthead 
    - Links images for footer
    - Links images for masthead

Updates can be viewed here:
https://deploy-preview-58--carbon-for-ibm.netlify.com/components/footer
https://deploy-preview-58--carbon-for-ibm.netlify.com/components/masthead

**Comment by JennySanchez** [comment]
**Update:** Reviewed and worked on the content update with Jacob last Friday.

**Comment by jacobottesen-dgc** [comment]
Component – Footer

https://deploy-preview-91--carbon-for-ibm.netlify.com/components/footer

Progress:

- Figure out heading style for ‘Rules’
- Figure out icon for ‘View sandbox’

——-

Component – Masthead

https://deploy-preview-91--carbon-for-ibm.netlify.com/components/masthead

Progress:

- Figure out icon for ‘View sandbox’


cc. @JennySanchez

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Both pages look good. I will create a task for us to add Anatomy and Behavior sections for the Footer page for Sprint 23 as discussed.
